version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/example/android"
    schedule:
      interval: "weekly"