name: double_tap_player_view
description: a widget to handle fast forward/rewind behavior by double tap and horizontal drag like a video player.
version: 2.0.3
homepage: https://github.com/HiroyukTamura/double_tap_player_view
repository: https://github.com/HiroyukTamura/double_tap_player_view

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  uuid: ^3.0.4
  freezed_annotation: ^2.2.0
  circular_reveal_animation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner:
  flutter_lints: ^2.0.1
